apiVersion: v1
kind: ConfigMap
metadata:
  name: sysdig-agent
data:
  dragent.yaml: |
    configmap: true
    ### Agent tags
    # tags: linux:ubuntu,dept:dev,local:nyc

    #### Sysdig Software related config ####

    # Sysdig collector address
    collector: collector-static.sysdigcloud.com

    # Collector TCP port
    collector_port: 6443

    # Whether collector accepts ssl
    ssl: true

    # collector certificate validation
    ssl_verify_certificate: true

    #######################################
    new_k8s: true
    k8s_cluster_name: kubernetes140
    prometheus:
        enabled: true
    chisels:
      - name: logwatcher
        args:
          filespattern: /var/lib/docker/containers/b16772be0eeac3c1a0cdf5abd172d547014e8fb76855844c94a6651d97375f18/b16772be0eeac3c1a0cdf5abd172d547014e8fb76855844c94a6651d97375f18-json.log
          term: access
