apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: kube-system
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 15Gi
  nfs:
    path: /var/nfsshare/pv01
    server: 192.168.1.22
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mysqlclass
