apiVersion: v1
kind: PersistentVolume
metadata:
  name: elastic-pv02
  namespace: kube-system
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  nfs:
    path: /var/nfsshare/pv06
    server: 192.168.1.22
  persistentVolumeReclaimPolicy: Retain
  storageClassName: elasticclass
