apiVersion: v1
kind: PersistentVolume
metadata:
  name: elastic-pv03
  namespace: kube-system
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  nfs:
    path: /var/nfsshare/pv07
    server: 192.168.1.22
  persistentVolumeReclaimPolicy: Retain
  storageClassName: elasticclass
