apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: kube-system
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 15Gi
  nfs:
    path: /opt/share/mysql
    server: 192.168.54.140
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mysql-storage
