apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: kube-system
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 15Gi
  nfs:
    path: /var/nfsshare/pv01
    server: 10.1.150.157
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mysqlclass
